config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :portfolios, except: [:show]

  get 'angular-items', to: 'portfolios#angular' # this isn't necessarily a best-practice
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= copyright_generator %></p>
    <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  </div>
</footer>

app/views/shared/_application_header.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">phex</h3>
    <nav class="nav nav-masthead justify-content-center <%= location %>">
        <%= link_to 'Home', root_path, :class => 'nav-link' %>
        <%= link_to 'Portfolio', portfolios_path, :class => 'nav-link' %>
        <%= link_to 'Blog', blogs_path, :class => 'nav-link' %>
        <%= link_to 'About', about_path, :class => 'nav-link' %>
        <%= link_to 'Contact', contact_path, :class => 'nav-link' %>
        <%= login_helper 'nav-link' %>
    </nav>
  </div>
<!--  <div class="inner">-->
<!--    <p class="notice alert alert-info"><%#= notice %></p>-->
<!--    <p class="alert alert-warning"><%#= alert %></p>-->
<!--  </div>-->
  <%#= source_helper('application') %>
</header>